[profile.default]
src = "src"
out = "out"
libs = ["lib"]
script = "script"
test = "test"
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
solc_version = "0.8.22"
# auto_detect_solc = true
verbosity = 3
block_timestamp = 0
block_gas_limit = 30000000
# auto_detect_remappings = true # recursive auto-detection of remappings

[fuzz]
runs = 5120
# max_test_rejects = 65536
seed = '0x2'
# dictionary_weight = 40
# include_storage = true
# include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
# call_override = false
# dictionary_weight = 80
# include_storage = true
# include_push_bytes = true
# shrink_sequence = true
# preserve_state = false

[fmt]
single_line_statement_blocks = "preserve"
override_spacing = false
line_length = 120
wrap_comments = true
number_underscore = "preserve"
tab_width = 4
bracket_spacing = false
quote_style = "double"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
